import paramiko, os, time
BASE = os.path.dirname(os.path.dirname(__file__))
c = paramiko.Transport(('119.23.51.159', 22))
c.connect(username='root', password='Yy@@##861018')
sftp = paramiko.SFTPClient.from_transport(c)
for f in ['server/simple.js', 'server/fetch_real_odds.js']:
    local = os.path.join(BASE, f)
    sftp.put(local, '/var/www/zj.100qiu.com/' + f)
    print(f'{f} OK ({os.stat(local).st_size}B)')
chan = c.open_session()
chan.exec_command('pm2 restart jc-zjfa')
chan.shutdown_write()
time.sleep(4)
chan.recv(4096)
chan.close()
print('PM2 restarted')
sftp.close()
c.close()
