import paramiko, os, time
BASE = os.path.dirname(os.path.dirname(__file__))
c = paramiko.Transport(('119.23.51.159', 22))
c.connect(username='root', password='Yy@@##861018')
sftp = paramiko.SFTPClient.from_transport(c)
sftp.put(os.path.join(BASE, 'server/simple.js'), '/var/www/zj.100qiu.com/server/simple.js')
print('simple.js deployed')
chan = c.open_session()
chan.exec_command('pm2 restart jc-zjfa')
chan.shutdown_write()
time.sleep(4)
chan.recv(4096)
chan.close()
print('jc-zjfa restarted')
sftp.close()
c.close()
