#------\u6807\u51C6\u53C2\u6570-----------
sign_type            = RSA
charset              = UTF-8
mer_id               = 6268
version              = 4.0
amt_type             = RMB
media_type           = MOBILE
notify_url           = http://www.quncai.com/user/umpayChargeNotify.php
#------END\u6807\u51C6\u53C2\u6570--------

#\u652F\u4ED8\u670D\u52A1\u53C2\u6570\u540D\uFF1Aservice
#\u652F\u4ED8\u7C7B\u578B\u53C2\u6570\u540D\uFF1Apay_type
#\u4EE5\u4E0B\u670D\u52A1\u53C2\u6570\u53CA\u652F\u4ED8\u7C7B\u578B\u53C2\u6570\u5C5E\u81EA\u5B9A\u4E49,\u4EE5\u793A\u533A\u5206

#-------\u7F51\u94F6\u76F4\u8FDE----------
direct_type          = B2CBANK
direct_server        = pay_req_split_direct
#-------\u7F51\u94F6\u76F4\u8FDE-----------

#-------\u4FE1\u7528\u5361\u4E00\u952E\u652F\u4ED8-------
credit_type          = CREDITCARD
credit_server        = pay_req_shortcut_front
#-------\u4FE1\u7528\u5361\u4E00\u952E\u652F\u4ED8-------

#-------SDK\u4E0B\u5355----------
sdk_order_server     = pay_req_shortcut
#-------SDK\u4E0B\u5355----------

#-------\u8054\u52A8\u652F\u4ED8\u67E5\u8BA2\u5355-------
query_order_service  = query_order
#-------\u8054\u52A8\u652F\u4ED8\u67E5\u8BA2\u5355-------

#-------HTML5\u4E0B\u5355\u8BF7\u6C42\u94FE\u63A5---
html5_order_url      = https://m.soopay.net/q/html5/index.do?
#-------HTML5\u652F\u4ED8\u8BF7\u6C42\u94FE\u63A5---

#-------wap\u652F\u4ED8\u8BF7\u6C42\u94FE\u63A5-----
wap_order_url        = https://m.soopay.net/q/xhtml/index.do?
#-------wap\u652F\u4ED8\u8BF7\u6C42\u94FE\u63A5-----


